baseURL = "https://heyiweiben.com/"
languageCode = "zh-cn"
title = "以为本"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 20